Error fix from enabling Clang thread-safety checks.
Parent bug: b/353324127. Enabling `thread-safety-reference-return`
to allow developers to utilize Clang thread safety guardrails
(GUARDED_BY, REQUIRES, EXCLUDES).

Error:
packages/modules/adb/client/adb_client.cpp:447:12: error: returning
variable 'features' by reference requires holding mutex
'feature_mutex' [-Werror,-Wthread-safety-reference-return]

Fix: return by value, hold mutex from parent, or remove GUARDED_BY
attribute.

This fix removes the GUARDED_BY attribute in order to avoid changing
functionality. If this is not desired, please respond with concerns
or preferred fix.

Bug: 353326460
Test: make
Change-Id: Ie2eca17de6c408afbaceada048882c38d028b078